# Generated by Django 2.0 on 2017-12-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBModel', '0002_user_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_reg',
        ),
    ]
